### ISSUE TITLE
[TO-DO] Tasks remaining

### ISSUE THREAD

**Issue by LePhenix47** [LePhenix47/Paintbrush_Younes-Lahouiti#1]
# To-do

- [x] Add a preview to the shape we're going to draw
![image](https://github.com/LePhenix47/Paintbrush_Younes-Lahouiti/assets/78600723/7e1b8732-659d-43d4-aced-6fe209b20658)

- [x] Change the mouse events on the event listeners + additional changes for the event type:
`mousemove` to `pointermove`
`mousedown` to `pointerdown`
`mouseup` to `pointerup`
- [x] Add filters for the canvas and for the shapes
- [x] Fix the scroll snapping effect 
- [ ] Fix bugs in the project

**Comment by LePhenix47** [comment]
## Useful sources: 

__HTML5 Canvas CRASH COURSE for Beginners by Franks Laboratory:__
https://www.youtube.com/watch?v=Yvz_axxWG4Y


__Learn Pointer Events In 15 Minutes by Web Dev Simplified:__
https://www.youtube.com/watch?v=MhUCYR9Tb9c

__Leam CSS Scroll Snap ln 6 Minutes by Web Dev Simplified:__
https://youtu.be/ytl6TrroGis
